config/routes.rb
Rails.application.routes.draw do
  resources :case_files

end

app/models/case_file.rb
# == Schema Information
#
# Table name: case_files
#
#  id           :integer          not null, primary key
#  event_date   :date
#  event_type   :string(255)
#  pti_urn      :string(255)
#  version      :integer
#  case_markers :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#


class CaseFile < ActiveRecord::Base


  composed_of :event, class_name: "Event", mapping: [ %w(event_date date),  %w(event_type type) ]
  validate :event_validation


  private

  def event_validation
    unless event.valid?
      event.errors.each { |e| errors[:event] << e }
    end
  end
  
end

app/models/case_marker.rb
class CaseMarker < DcfEnum

  @@valid_values = %w{ AE CO DH DV FM FT HC HP LO NU PW RA RE RP TG }
end

app/models/event.rb
class Event

  EVENT_TYPES =  %w{ CaseFile }

  attr_reader :date, :type, :errors

  def initialize(date, type)
    @date = date
    @type = type
    @errors = []
    validate
  end

  def valid?
    @errors.empty?
  end

  private

  def validate
    return if @date.nil? && @type.nil?
    @errors << "Invalid Date" if @date > Date.today
    @errors << "Invalid Event Type" unless EVENT_TYPES.include?(@type)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/case_files_controller.rb
class CaseFilesController < ApplicationController
  before_action :set_case_file, only: [:show, :edit, :update, :destroy]

  # GET /case_files
  # GET /case_files.json
  def index
    @case_files = CaseFile.all
  end

  # GET /case_files/1
  # GET /case_files/1.json
  def show
  end

  # GET /case_files/new
  def new
    @case_file = CaseFile.new
  end

  # GET /case_files/1/edit
  def edit
  end

  # POST /case_files
  # POST /case_files.json
  def create
    @case_file = CaseFile.new(case_file_params)

    respond_to do |format|
      if @case_file.save
        format.html { redirect_to @case_file, notice: 'Case file was successfully created.' }
        format.json { render :show, status: :created, location: @case_file }
      else
        format.html { render :new }
        format.json { render json: @case_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /case_files/1
  # PATCH/PUT /case_files/1.json
  def update
    respond_to do |format|
      if @case_file.update(case_file_params)
        format.html { redirect_to @case_file, notice: 'Case file was successfully updated.' }
        format.json { render :show, status: :ok, location: @case_file }
      else
        format.html { render :edit }
        format.json { render json: @case_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /case_files/1
  # DELETE /case_files/1.json
  def destroy
    @case_file.destroy
    respond_to do |format|
      format.html { redirect_to case_files_url, notice: 'Case file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_case_file
      @case_file = CaseFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def case_file_params
      params.require(:case_file).permit(:event_type, :event_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/case_files/_form.html.erb
<%= form_for(@case_file) do |f| %>
  <% if @case_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@case.errors.count, "error") %> prohibited this case from being saved:</h2>

      <ul>
      <% @case_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_date %><br>
    <%= f.date_select :event_date %>
  </div>
  <div class="field">
    <%= f.label :event_type %><br>
    <%= f.text_field :event_type %>
  </div>
  <div class="field">
    <%= f.label :pti_urn %><br>
    <%= f.text_field :pti_urn %>
  </div>
  <div class="field">
    <%= f.label :version %><br>
    <%= f.number_field :version %>
  </div>
  <div class="field">
    <%= f.label :case_markers %><br>
    <%= f.text_field :case_markers %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/case_files/edit.html.erb
<h1>Editing Case</h1>

<%= render 'form' %>

<%= link_to 'Show', @case_file %> |
<%= link_to 'Back', case_files_path %>

app/views/case_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cases</h1>

<table>
  <thead>
    <tr>
      <th>Event date</th>
      <th>Event type</th>
      <th>Pti urn</th>
      <th>Version</th>
      <th>Case markers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @case_files.each do |case_file| %>
      <tr>
        <td><%= case_file.event_date %></td>
        <td><%= case_file.event_type %></td>
        <td><%= case_file.pti_urn %></td>
        <td><%= case_file.version %></td>
        <td><%= case_file.case_markers %></td>
        <td><%= link_to 'Show', case_file %></td>
        <td><%= link_to 'Edit', edit_case_file_path(case_file) %></td>
        <td><%= link_to 'Destroy', case_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Case', new_case_file_path %>

app/views/case_files/new.html.erb
<h1>New Case</h1>

<%= render 'form' %>

<%= link_to 'Back', case_files_path %>

app/views/case_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event date:</strong>
  <%= @case_file.event_date %>
</p>

<p>
  <strong>Event type:</strong>
  <%= @case_file.event_type %>
</p>

<p>
  <strong>Pti urn:</strong>
  <%= @case_file.pti_urn %>
</p>

<p>
  <strong>Version:</strong>
  <%= @case_file.version %>
</p>

<p>
  <strong>Case markers:</strong>
  <%= @case_file.case_markers %>
</p>

<%= link_to 'Edit', edit_case_file_path(@case_file) %> |
<%= link_to 'Back', case_files_path %>

app/views/cases/_form.html.erb
<%= form_for(@case) do |f| %>
  <% if @case.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@case.errors.count, "error") %> prohibited this case from being saved:</h2>

      <ul>
      <% @case.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_date %><br>
    <%= f.date_select :event_date %>
  </div>
  <div class="field">
    <%= f.label :event_type %><br>
    <%= f.text_field :event_type %>
  </div>
  <div class="field">
    <%= f.label :pti_urn %><br>
    <%= f.text_field :pti_urn %>
  </div>
  <div class="field">
    <%= f.label :version %><br>
    <%= f.number_field :version %>
  </div>
  <div class="field">
    <%= f.label :case_markers %><br>
    <%= f.text_field :case_markers %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cases/new.html.erb
<h1>New Case</h1>

<%= render 'form' %>

<%= link_to 'Back', cases_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dcf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>